spring:
  datasource:
    url: jdbc:h2:mem:ecommerceDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console.enabled: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace